### ISSUE TITLE
Reading group papers

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/2021summer#1]
The first meeting for the reading group will be Tuesday, 25 May at 8am on zoom.  The paper we'll read is: https://www.aclweb.org/anthology/2020.wac-1.2/

Please spend at least 1 hour reading the paper before our first meeting.  To focus your reading, try to understand the following questions:
1. What problem is the paper trying to solve?
2. What are the unique contributions of this paper compared to prior work?
3. What are the limitations of the paper? (or ways the paper could be improved)

During the meeting, I will lead a discussion addressing these and other points.

**Comment by saatvik7** [comment]
Hi Mike, 
What's the Zoom link for the meeting?

**Comment by mikeizbicki** [comment]
Same link we used for class.  I don't want to post it here though since it's likely to get scraped and abused.

**Comment by mikeizbicki** [comment]
Next week's paper is: https://www.aclweb.org/anthology/2020.wac-1.3/

**Comment by mikeizbicki** [comment]
The next main paper I want to read is: https://www.microsoft.com/en-us/research/publication/improving-document-ranking-with-dual-word-embeddings/

It's a short paper, but it depends on the word2vec algorithm.  So we'll also talk about word2vec first
1. using this blog post: https://blog.acolyer.org/2016/04/21/the-amazing-power-of-word-vectors/
2. and this actual paper: http://arxiv.org/pdf/1402.3722v1.pdf

Focus on the blog post and word2vec paper this week, then next week we'll tackle the microsoft paper.

**Comment by mikeizbicki** [comment]
We'll read https://academic.oup.com/isq/advance-article/doi/10.1093/isq/sqab029/6278490 next week, which is a political science paper using sentiment analysis of newspapers and talk about its weaknesses from a cs perspective.  Then the following weak we'll read https://www.aclweb.org/anthology/2020.acl-main.370/ which is a cs paper using sentiment analysis, and we'll see how the two papers take very different approaches to similar problems.  The latter paper is a hard read, so try to fully understand it in just one sitting---spread it out over multiple days.

**Comment by mikeizbicki** [comment]
For our next papers, I want us to read about different types of websearch beyond what google is doing.

On 13 July we'll go over [Building an Argument Search Engine for the Web](https://aclanthology.org/W17-5106/)

We'll skip the meeting on 20 July.

Then 27 July we'll go over [Syntactic Search by Example](https://aclanthology.org/2020.acl-demos.3/)

**Comment by mikeizbicki** [comment]
We're going to do something a bit different next week and look at an industry product instead of a research paper.  The product is https://www.shodan.io/ which is a search engine for computers connected to the internet.  It does a lot of things, but it's most famous for letting you search for computers that you can hack into.

There's lots of interesting things about this search engine that are different than other search engines (technical details about what it searches, ethical issues, its business model without ads).  For next week, I want you to play around with the search engine a bit and do 2 things:

1. try to create the most interesting search query that you can (you'll have to create a free account to run queries), and we'll have a quick competition to see who created the most interesting query
2. write down any questions you have about how it works / ethics / etc so we can talk about them in the meeting

There's no particular paper to read.  Instead, I recommend the following simple tutorial: https://danielmiessler.com/study/shodan/ 

There's also some good video tutorials from a conference called DEFCON.  DEFCON is a hacking conference that has a weird mix of academic researchers, black hat criminals, and FBI agents all presenting and sharing their work.  Some Shodan videos from the conference are:
1. https://www.youtube.com/watch?v=js840O9zHTE
2. https://www.youtube.com/watch?v=-T-3buBwMEQ

There's no requirement to watch those videos, but they'll give you a good sense of the types of things you can accomplish with shodan.

**Comment by mikeizbicki** [comment]
In addition to the paper tomorrow, I'm going to mention a quick way that you all can contribute to @tonnpo's research by doing some data labeling.  It certainly won't be required for you to participate, but for those of you who'd like to we will include you as a coauthor on a paper that we're writing together.  I'd estimate that the work load would be 20-40 hours depending on how fast you work.

**Comment by mikeizbicki** [comment]
For anyone not on the email thread, tomorrow we are not going over a paper but instead talking about @Tonnpo's research in more detail and how to contribute.

**Comment by mikeizbicki** [comment]
I think I forgot to mention this before, but I was intending last week's group meeting to be the last one of the summer.  So we won't meet as a group tomorrow.

For @Tonnpo, @valenxie, and @joeybodoia, we'll still have the 1-1 meetings tomorrow at the normal times.
