### ISSUE TITLE
ImportError: cannot import name 'to_query'

### ISSUE THREAD

**Issue by joeybodoia** [mikeizbicki/2021summer#3]
Hey Mike, 

I believe that I was able to get all the dependencies installed correctly after I switched to using the lambda server, and so I moved on to testing/debugging the `augments.py` file in the python interpreter. 

Given that there are local imports in the `augments.py` file, I have been using the python interpreter in the same way that we did with BST during class. That is, instead of running the interpreter with a specific file like this:
```
python3 -i chajda/tsquery/augments.py
```
I ran the interpreter without a specific file:
```
python3 -i
```
and then imported directly into the interpreter.
I tried the following imports:
```
import chajda.tsquery
```
```
import chajda.tsvector
```
```
import chajda.tsquery.augments
```
Which resulted in this error:
```
>>> import chajda.tsquery
>>> import chajda.tsvector
>>> import chajda.tsquery.augments
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Joseph.Bodoia.21/summer_research/chajda/tsquery/augments.py", line 5, in <module>
    from chajda.tsquery import to_tsquery
ImportError: cannot import name 'to_tsquery'
```
I then exited the interpreter and reopened it, and tried:
```
from chajda.tsquery import to_tsquery
```
which gave the same error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'to_tsquery'
```
From what I've seen on stackoverflow, it seems like `ImportError: cannot import name X` is usually caused by circular dependent imports. However, it doesn't seem like there are circular dependent imports in this case.

Furthermore, I added a new function in the `tsquery.py` file:
```
def test():
     print("test")
```
And then opened the interpreter and ran:
```
from chajda.tsquery import test
```
which gave the same import error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'test'
```

Any thoughts on what might be going on? I've been trying to troubleshoot this for a while now, and would greatly appreciate any advice you might have. 

Thank you for your time,

Joey

**Comment by mikeizbicki** [comment]
You're experiencing a classic module problem in python.  Modules are handled really poorly in python, and it's one of the major complaints people have about it compared to other languages.

First, I reproduced your steps on the lambda server, but then I ran the following command in the python interpretter
```
>>> import chajda.tsquery
>>> chajda.tsquery.__file__
'/home/Joseph.Bodoia.21/summer_research/chajda/tsquery/__init__.py'
```
The `__file__` variable contains the name of the file on the harddrive.  As you can see, this does not correspond to the `chajda/tsquery.py` file that it's supposed to.  What's happened is that you've created this `__init__.py` file in the `tsquery` folder, and this is causing python to load that file instead of `chajda/tsquery.py` as the `chajda.tsquery` module.

If you delete this `__init__.py` file, then everything should work again.

**Comment by joeybodoia** [comment]
That makes sense, thanks Mike.

However, this leads to another issue. The reason that I originally added the `__init__.py` file into the tsquery folder was to troubleshoot an error that I was getting when I tried to import `chajda.tsquery.augments' in the python interpreter. That is, I opened the python interpreter from the root of the repo, and then ran:
```
>>> import chajda.tsquery.augments
```
which resulted in this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'chajda.tsquery.augments'; 'chajda.tsquery' is not a package
>>> 
```
That being said, adding the `__init__.py` file to the tsquery folder allowed me to access the `augments.py` file, but clearly caused a new issue (ImportError: cannot import name 'to_tsquery')

After removing the `__init__.py` file, I am now able to successfully import `to_tsquery` from the `tsquery.py` file:
```
>>> from chajda.tsquery import to_tsquery
```
However, I now run into my original issue of not being able to import the `augments.py` file in the interpreter:
I tried:
```
>>> import chajda.tsquery.augments
```
which resulted in this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'chajda.tsquery.augments'; 'chajda.tsquery' is not a package
```
It seems like this is probably a syntactical issue of importing a file that is in nested folders, which leads me to my final question: 
How do I import a file, `augments.py`, that is inside nested folders, into the python interpreter without having to `cd` into  `chajda`. That is, `augments.py` is inside `tsquery `folder which is inside the `chajda` folder.

To reiterate my overall issue:
I'm trying to debug `chajda/tsquery/augments.py`, which uses local imports from `chajda/tsvector` and `chajda/tsquery`. I would like to open a python interpreter in the root of the repo and import the following files:
```
import chajda/tsquery.py
import chajda/tsvector.py
import chajda/tsquery/augments.py
```

Hopefully this makes sense, I'm happy to elaborate further if anything is unclear.

**Comment by mikeizbicki** [comment]
Hmm... let's rename the `chajda/tsquery.py` file to `chajda/tsquery/__init__.py`.  That should fix both problems.

**Comment by joeybodoia** [comment]
Great, that worked.

Thanks, Mike

**Comment by mikeizbicki** [comment]
I just realized this was posted under the 2021summer repo instead of the chajda repo.  In the future, it'll make more sense to put this sort of question under the chajda repo since it directly concerns code from that repo.  That'll make it easier for other people to find these issues who are working on that repo in the future.
